/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package memorygame_desktopedition;

import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import static memorygame_desktopedition.GameWindow.connection;
import static memorygame_desktopedition.GameWindow.theme;

/**
 *
 * @author justw
 */
public class Leaderboard extends javax.swing.JDialog {

    int thisTheme = theme;

    public Leaderboard(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        GetResults();
        FormatTables();
        SetDropDown();
    }

    private void SetDropDown() {
        themeDropDown.setSelectedIndex(theme - 1);
    }

    private String getThemeString(int t) {
        switch (t) {
            case 1:
                return "Animals";
            case 2:
                return "Save Earth";
            case 3:
                return "Food";
            case 4:
                return "Medieval";
            case 5:
                return "Programming";
            case 6:
                return "Sea";
        }
        return "Animals";
    }

    private int getThemeInt(String s) {
        switch (s) {
            case "Animals":
                return 1;
            case "Save Earth":
                return 2;
            case "Food":
                return 3;
            case "Medieval":
                return 4;
            case "Programming":
                return 5;
            case "Sea":
                return 6;
        }
        return 1;
    }

    private void GetResults() {
        DefaultTableModel model = (DefaultTableModel) timesTable.getModel();
        model.setRowCount(0);
        //int thm = getThemeString(thisTheme);
        String sqlQuery = "";
        Object arr[] = new Object[3];
        sqlQuery = "select * from times where theme='" + thisTheme + "' order by time asc";
        try (Statement s0 = connection.createStatement()) {
            ResultSet rs0 = s0.executeQuery(sqlQuery);
            while (rs0.next()) {
                arr[0] = rs0.getString("playerName");
                arr[1] = getThemeString(rs0.getInt("theme"));
                arr[2] = rs0.getString("time");
                FillTimesTable(arr);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void FillTimesTable(Object arr[]) {
        DefaultTableModel model = (DefaultTableModel) timesTable.getModel();
        model.addRow(arr);
    }

    private void FormatTables() {
        DefaultTableCellRenderer columnRenderer = new DefaultTableCellRenderer();
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        columnRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        headerRenderer = (DefaultTableCellRenderer) timesTable.getTableHeader().getDefaultRenderer();
        headerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        timesTable.getColumnModel().getColumn(0).setCellRenderer(columnRenderer);
        timesTable.getColumnModel().getColumn(1).setCellRenderer(columnRenderer);
        timesTable.getColumnModel().getColumn(2).setCellRenderer(columnRenderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        timesTable = new javax.swing.JTable();
        themeDropDown = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Leaderboard");
        jLabel1.setAlignmentX(0.5F);

        timesTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        timesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Player Name", "Theme", "Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(timesTable);

        themeDropDown.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        themeDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Animals", "Save Earth", "Food", "Medieval", "Programming", "Sea" }));
        themeDropDown.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                themeDropDownItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(themeDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(themeDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void themeDropDownItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_themeDropDownItemStateChanged
        thisTheme = themeDropDown.getSelectedIndex() + 1;
        GetResults();
    }//GEN-LAST:event_themeDropDownItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Leaderboard dialog = new Leaderboard(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> themeDropDown;
    private javax.swing.JTable timesTable;
    // End of variables declaration//GEN-END:variables
}
